---
resource_types:
  - name: email
    type: registry-image
    source:
      repository: pcfseceng/email-resource

resources:
  - name: config
    icon: git
    type: git
    source: ((k0sctl.config))

  - name: backup
    icon: git
    type: git
    source: ((k0sctl.backup))

  - name: ping
    icon: check-network
    type: time
    source: ((timer.ping))

  - name: backup
    icon: backup-restore
    type: time
    source: ((timer.backup))

  - name: k0sctl
    icon: lambda
    type: registry-image
    source:
      repository: omegasquad82/k0sctl-handler

  - name: email
    icon: email-alert
    type: email
    source: ((email))

shell_task: &shell_task
  image: k0sctl
  config: &shell_config
    platform: linux
    inputs:
      - name: config
      - name: restore
    outputs:
      - name: auditlog
      - name: backup

k0sctl_task: &k0sctl_task
  task: k0sctl
  image: k0sctl
  config: &k0sctl_config
    platform: linux
    inputs:
      - name: config
        optional: true
      - name: restore
        optional: true
      - name: auditlog
        optional: true
    outputs:
      - name: auditlog
      - name: backup
      - name: config
    params: &k0sctl_params
      DISABLE_TELEMETRY: ((k0sctl.flags.no_telemetry))
      MAILBOX: ((k0sctl.cluster.mail))
      SSH_KEY: ((k0sctl.cluster._key))
    run:
      path: k0sctl-handler.sh

jobs:
  - name: ping
    public: true
    serial: true
    plan:
      - do:
          - in_parallel:
              - get: ping
                trigger: true
              - get: config
                trigger: true
              - get: k0sctl
          - <<: *shell_task
            task: discover
            config:
              <<: *shell_config
              run:
                path: bash
                user: root
                args:
                  - -c
                  - |
                    . common.sh
                    tracerouteSSH config/k0sctl.yaml
        on_failure: &notify_failure
          put: email
          inputs:
            - auditlog
          params:
            subject_text: "((k0sctl.cluster.name)): k0sctl execution failed"
            body_text: "please see attachments for further analysis"
            attachment_globs: ["auditlog/*"]

  # https://docs.k0sproject.io/latest/k0sctl-install/#install-using-k0sctl
  - name: install
    serial_groups: [k0sctl]
    plan:
      - do:
          - in_parallel:
              - get: config
                trigger: true
                passed: [ping]
              - get: restore
                resource: backup
              - get: k0sctl
          - <<: *k0sctl_task
            params:
              <<: *k0sctl_params
              K0SCTL_CMD_NAME: install
        on_failure:
          <<: *notify_failure
        on_success: &notify_success
          put: email
          inputs:
            - auditlog
          params:
            subject_text: "((k0sctl.cluster.name)): k0sctl execution succeeded"
            body_text: "please see attachments for further analysis"
            attachment_globs: ["auditlog/*"]

  # https://docs.k0sproject.io/latest/backup/#backuprestore-a-k0s-cluster-using-k0sctl
  - name: init
    serial: true
    plan:
      - in_parallel:
          - get: restore
            resource: backup
          - get: k0sctl
      - <<: *shell_task
        task: prepare
        config:
          <<: *shell_config
          run:
            path: bash
            user: root
            args:
              - -c
              - |
                . common.sh
                runCMD git clone restore backup
                prepareGIT backup ((k0sctl.cluster.mail))
                initBranch ((k0sctl.backup.branch))
        on_success:
          put: backup
          params:
            force: true # drop
            repository: backup
  - name: backup
    serial_groups: [k0sctl]
    plan:
      - do:
          - in_parallel:
              - get: backup
                trigger: true
              - get: restore
                resource: backup
              - get: config
                trigger: true
                passed: [install]
              - get: k0sctl
          - <<: *k0sctl_task
            params:
              <<: *k0sctl_params
              K0SCTL_CMD_NAME: backup
            on_success:
              put: backup
              params:
                rebase: true
                repository: backup
        on_failure:
          <<: *notify_failure
        on_success:
          <<: *notify_success

  # https://docs.k0sproject.io/latest/reset/#uninstall-a-k0s-cluster-using-k0sctl
  - name: uninstall
    serial_groups: [k0sctl]
    plan:
      - do:
          - in_parallel:
              - get: config
                passed: [ping]
              - get: k0sctl
          - <<: *k0sctl_task
            params:
              <<: *k0sctl_params
              K0SCTL_CMD_NAME: uninstall
        on_failure:
          <<: *notify_failure
        on_success:
          <<: *notify_success
