name: buildx ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  TESTING_TAG: omegasquad82/k0sctl-handler:test
  RELEASE_TAG: omegasquad82/k0sctl-handler:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ env.TESTING_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.TESTING_TAG }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.RELEASE_TAG }}
